defaults:
    - _self_
    - task: imagepressure2smpl

wandb_mode: disabled
wandb_project: MotionPRO
wandb_entity: davyfangyuxuan-nanjing-university-of-aeronautics-and-ast
    
# hydra parameters
hydra:
  run:
    dir: ${oc.env:ANYSOLE_RESULTS,../../results}/MotionPRO/logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
