subject: ''
scene_rgbd: ''
input_path_base: ''
thres_contact: 15

image_width: 1624
image_height: 1240
focal_length: 1394
scale: 0.97
depth_scale: 1.0
fps: 40.0
max_frames: 0
output_path: ''
write_visualization: true
