subject: 'S10'
scene_rgbd: 'D:/Dataset/test/MMVP/template_scene_rgbd.npy'
input_path_base: 'D:/Dataset/test/MMVP'
thres_contact : 15

image_width: 1624
image_height: 1240
focal_length: 1394
scale: 0.97
depth_scale: 1.0
fps: 40.0